import type { Metadata } from "next";
import React from "react";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Next.js App with Tailwind",
  description: "Generated by Next.js 15 and Tailwind CSS",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
